version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}

      - run:
          name: Install Dependencies
          command: |
            poetry config virtualenvs.path /home/circleci/project/
            poetry install

      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - .

      - run:
          name: Exec Pytest
          command: |
            poetry run pytest
            pytest
