version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: set up environment variables
          command: echo "export CACHE_PATH=/home/circleci/.cache/pypoetry/virtualenvs >> $BASH_ENV"

      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}

      - run:
          name: Install Dependencies
          command: |
            poetry config virtualenvs.path /home/circleci/.cache/pypoetry/virtualenvs
            poetry install

      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - CACHE_PATH

      # - run:
      #     name: Exec Pytest
      #     command: |
      #       pytest
